version: "3"
services:
    www:
        build: ./php
        ports: 
            - "8001:80"
        volumes:
            - ./php/blog:/var/www/html
    db:
        image: mariadb:10.4
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: newblog
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8000:80"
        environment:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_ROOT_PASSWORD:
    dozzle:
        image: amir20/dozzle:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "9999:8080"
